application:
  name: nuxt
  project: CHANGEME
  cpu: 800m
  ram: 512mb
  start_timeout: 480s
  publicly_accessible: true
routers:
  - name: main
    routes:
      - application_name: nuxt
        paths:
          - /*
